In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,"es","luv",5])

In [4]:
arr.dtype

dtype('<U11')

In [5]:
np.sum(arr)

TypeError: cannot perform reduce with flexible type

In [6]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])

In [7]:
arr.shape

(3, 3)

In [9]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [10]:
arr= np.random.randn(3,4)

In [11]:
arr

array([[ 0.970349  , -0.17595138,  0.9593143 , -2.4069601 ],
       [-2.57142809,  1.09064064, -2.12953432,  1.24115057],
       [-0.22747797, -0.92579186,  0.04479305, -1.56331995]])

In [12]:
import pandas as pd
b = pd.read_csv("citation-281175281.txt")

In [13]:
arr = np.genfromtxt(b, delimiter = ",")

In [15]:
arr

array([nan, nan, nan])

In [16]:
arr = np.array([[1,2,3],[2,4,6][8,8,8]])

TypeError: list indices must be integers or slices, not tuple

In [17]:
arr = np.zeros((2,4))

In [18]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr = np.ones((2,4))

In [20]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr = np.identity(3)

In [22]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.random.randn(3,4)

In [24]:
arr

array([[ 0.27646651,  0.95247054, -0.6270555 ,  0.22415217],
       [ 2.2023103 , -0.0733803 , -1.22354061, -1.56781286],
       [-1.47323402,  0.14637812,  1.41755386,  1.07467719]])

In [25]:
arr = np.arange(12).reshape(2,2,3)

In [26]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
arr = np.arange(10)

In [29]:
arr[5:]

array([5, 6, 7, 8, 9])

In [30]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [32]:
arr = np.arange(12).reshape(2,2,3)

In [33]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
cities = np.array(["delhi", "bangalore", "mumbai", "chennai", "bhopal"])

In [36]:
city_data = np.random.randn(5,3)

In [37]:
city_data[cities == "delhi"]

array([[ 0.30649707, -0.42021925, -1.62734358]])

In [38]:
city_data[city_data>0]

array([0.30649707, 1.42823928, 0.89748831, 0.08173054, 0.73471696])

In [39]:
city_data[city_data>0] = 0

In [40]:
city_data

array([[ 0.        , -0.42021925, -1.62734358],
       [-0.30050231, -0.20436956, -0.19497621],
       [ 0.        ,  0.        , -0.81822258],
       [ 0.        , -0.52726226, -1.10027947],
       [ 0.        , -2.29297281, -0.86730536]])

In [41]:
arr = np.arange(15).reshape(3,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
arr+5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
arr*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [45]:
arr1 = np.arange(15).reshape(5,3)

In [46]:
arr2 = np.arange(5).reshape(5,1)

In [47]:
arr1 + arr2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [48]:
arr1 = np.random.randn(5,3)

In [49]:
arr1

array([[ 0.00837739, -0.41229452, -0.70381694],
       [ 2.45929835, -0.42759544, -1.21668201],
       [-0.42963502,  1.19564194, -1.57648462],
       [ 0.41368744, -0.35133414, -0.86276258],
       [-0.33192112, -2.30729824,  1.18801397]])

In [50]:
np.modf(arr1)

(array([[ 0.00837739, -0.41229452, -0.70381694],
        [ 0.45929835, -0.42759544, -0.21668201],
        [-0.42963502,  0.19564194, -0.57648462],
        [ 0.41368744, -0.35133414, -0.86276258],
        [-0.33192112, -0.30729824,  0.18801397]]), array([[ 0., -0., -0.],
        [ 2., -0., -1.],
        [-0.,  1., -1.],
        [ 0., -0., -0.],
        [-0., -2.,  1.]]))

In [51]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
B = np.array([[9,8,7],[6,5,4],[1,2,3]])

In [54]:
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [55]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
np.linalg.svd(A)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [57]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [58]:
b = np.array([16,-8,0])

In [59]:
x= np.linalg.solve(a,b)

In [60]:
x

array([1., 3., 2.])

In [61]:
np.allclose(np.dot(a,x),b)

True